Alternative to hardcoding image names in tests
user-cont/conu pull request #375
Opened 2019-12-16 00:39 UTC by kmehant

fixes #324

2019-12-16 07:39 UTC, rpitonak commented
/packit copr-build

2019-12-16 07:40 UTC, rpitonak commented
[test]

2020-01-07 09:20 UTC, TomasTomecek commented
/packit build

2020-01-07 09:22 UTC, TomasTomecek reviewed
Looks good!

Can we bump the test images to fedora:31? :) to make sure this works globally

2020-01-07 13:45 UTC, kmehant commented
@TomasTomecek I have updated to version 31 wherever possible :)

2020-01-07 15:45 UTC, TomasTomecek commented
/packit build

2020-01-07 15:46 UTC, TomasTomecek commented
[test]

2020-01-08 11:22 UTC, TomasTomecek reviewed
the CI failure:
```
17:02:26 Trying to pull registry.fedoraproject.org/fedora...
17:02:26   Get https://registry.fedoraproject.org/v2/fedora/manifests/sha256:687fe5e65ecc0d3082318b1285dfc553b2a5d794c6c0831155c303fdf328de90: net/http: TLS handshake timeout
17:02:26 Error: error pulling image "registry.fedoraproject.org/fedora": unable to pull registry.fedoraproject.org/fedora: unable to pull image: Error determining manifest MIME type for docker://registry.fedoraproject.org/fedora:latest: Get https://registry.fedoraproject.org/v2/fedora/manifests/sha256:687fe5e65ecc0d3082318b1285dfc553b2a5d794c6c0831155c303fdf328de90: net/http: TLS handshake timeout
```

2020-01-08 11:22 UTC, TomasTomecek commented on tests/constants.py
> +FEDORA_MINIMAL_IMAGE_REGEX = "registry\.fedoraproject\.org\/fedora-minimal\:+([0-9])+"
```suggestion
FEDORA_MINIMAL_IMAGE_REGEX = r"registry\.fedoraproject\.org\/fedora-minimal\:+([0-9])+"
```
there are warnings in a test run that `\.` is an unknown escape sequence

2020-01-09 08:45 UTC, TomasTomecek commented
[test]

2020-01-09 08:45 UTC, TomasTomecek commented
/packit build

2020-01-09 08:53 UTC, TomasTomecek commented
tried to run the podman tests locally and got a single error:
```
_____________________________________________________________________________ test_podman_image _____________________________________________________________________________
                                                                                                                                                                             
podman_backend = <conu.backend.podman.backend.PodmanBackend object at 0x7fb4aa4c3c10>                                                                                        
                                                                                                                                                                             
    def test_podman_image(podman_backend):                                                                                                                                   
        """
        Test interaction with an image
        """
        image = podman_backend.ImageClass(FEDORA_MINIMAL_REPOSITORY, tag=FEDORA_MINIMAL_REPOSITORY_TAG)
        assert "%s:%s" % (FEDORA_MINIMAL_REPOSITORY, FEDORA_MINIMAL_REPOSITORY_TAG) == image.get_full_name()
        assert "%s:%s" % (FEDORA_MINIMAL_REPOSITORY, FEDORA_MINIMAL_REPOSITORY_TAG) in image.inspect()['RepoTags']
        assert "Config" in image.inspect()
>       assert re.match(FEDORA_MINIMAL_NAME_REGEX, image.get_full_name())
E       AssertionError: assert None
E        +  where None = <function match at 0x7fb4c308b290>('fedora-minimal:([0-9])+', 'registry.fedoraproject.org/fedora-minimal:31')
E        +    where <function match at 0x7fb4c308b290> = re.match
E        +    and   'registry.fedoraproject.org/fedora-minimal:31' = <bound method PodmanImage.get_full_name of PodmanImage(repository=registry.fedoraproject.org/fedora-mini
mal, tag=31)>()
E        +      where <bound method PodmanImage.get_full_name of PodmanImage(repository=registry.fedoraproject.org/fedora-minimal, tag=31)> = PodmanImage(repository=registry
.fedoraproject.org/fedora-minimal, tag=31).get_full_name

image      = PodmanImage(repository=registry.fedoraproject.org/fedora-minimal, tag=31) 
podman_backend = <conu.backend.podman.backend.PodmanBackend object at 0x7fb4aa4c3c10>
```

2020-01-09 09:28 UTC, TomasTomecek requested changes
please fix the `test_buildah_image`, `test_image` and `test_podman_image` failures and we're good to merge; other test failures are unrelated

2020-01-14 05:26 UTC, kmehant commented
@TomasTomecek This is my local test report on total I have fixed `test_buildah_image PASSED` `test_podman_image 
 PASSED` `test_image PASSED` as you have mentioned :)
``` python
test_podman.py ALL TESTS PASSED

test_buildah.py 2 TESTS FAILED
     test_buildah_image PASSED
     test_container_metadata FAILED
     test_image_metadata FAILED

test_docker.py 1 TESTS FAILED
     test_image PASSED   
     test_copy_from FAILED
```

2020-01-16 14:51 UTC, TomasTomecek commented
[test]

2020-01-16 14:51 UTC, TomasTomecek commented
/packit build

2025-06-10 17:57 UTC, closed without merging